version: "3.3"

services:
  web:
    build: .
    ports:
      - "5000:5000"
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  nginx-conf:
