
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t my-app .
        docker tag my-app my-dockerhub-azat279/my-app:latest
        docker push my-dockerhub-azat279/my-app:latest

    - name: Deploy to server via SSH
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} user@192.168.56.82 "
          docker ps -q -f name=my-app | grep -q . && docker stop my-app && docker rm my-app || true
          docker pull my-dockerhub-azat279/my-app:latest &&
          docker run -d --name my-app my-dockerhub-azat279/my-app:latest
        "

