name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
<<<<<<< HEAD
          docker build -t ${{ secrets.DOCKER_USERNAME }}/webapp ./app
=======
          docker build -t ${{ secrets.DOCKER_USERNAME }}/webapp ./Devops-Project
>>>>>>> updated and fixed
          docker push ${{ secrets.DOCKER_USERNAME }}/webapp
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx ./nginx
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx

      - name: Deploy to Remote Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} user@192.168.56.82 "
            docker-compose -f /path/to/docker-compose.yml pull &&
            docker-compose -f /path/to/docker-compose.yml up -d
          "

