name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Запуск пайплайна при пуше в основную ветку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Проверка кода из репозитория

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Настройка Docker Buildx для мульти-платформенных сборок

    - name: Build Docker image
      run: |
        docker build -t my-app .  # Создание Docker-образа с тегом "my-app"
        docker tag my-app my-dockerhub-username/my-app:latest  # Тегирование образа для Docker Hub
        docker push my-dockerhub-username/my-app:latest  # Публикация образа в Docker Hub (если публичный)

    - name: Deploy to server via SSH
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} user@your-server-ip "
          docker pull my-dockerhub-username/my-app:latest &&  # Загрузка образа с Docker Hub
          docker stop my-app || true &&  # Остановка текущего контейнера (если работает)
          docker rm my-app || true &&  # Удаление контейнера
          docker run -d --name my-app my-dockerhub-username/my-app:latest  # Запуск нового контейнера с образом
        "
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Использование приватного ключа для подключения

